const VEHICLECONSTANT = {
  'CARSIZE': 'SMALL',
  'CARWEIGHT': 100,
  'BUSSIZE': 'LARGE',
  'BUSWEIGHT': 200,
  'MOTORCYCLESIZE': 'XSMALL',
  'MOTORCYCLEWIEGHT': 50
};

module.exports = VEHICLECONSTANT;